# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('added_dttm', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('last_modified_dttm', models.DateTimeField(default=datetime.datetime.now)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=32)),
                ('currency', models.CharField(choices=[('BTC', 'bitcoin'), ('ETH', 'etherium'), ('PHP', 'pesos')], max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'account',
            },
        ),
    ]
