# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('added_dttm', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('last_modified_dttm', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from_acc', to='accounts.Account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_to_acc', to='accounts.Account')),
            ],
            options={
                'abstract': False,
                'db_table': 'transaction',
            },
        ),
    ]
